services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      PORT: 4000
      REDIS_URL: redis://redis:6379
      BASE_PUBLIC_URL: http://localhost:4000
    ports:
      - "4000:4000"
    depends_on:
      redis:
        condition: service_started

  worker:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npm run worker"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      redis:
        condition: service_started

  frontend:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      BACKEND_URL: http://backend:4000
    ports:
      - "5173:5173"
    depends_on:
      - backend
